# -*- coding: utf-8 -*-
"""Customer_Shopping_Behavior.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JbpaKsl2_AANhuiq8HWSM_jryW6sJC-k
"""

import pandas as pd

df=pd.read_csv("/content/customer_shopping_behavior.csv")
df

df.head()

df.info()

df.describe(include='all')

df.isnull().sum()

df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

df['Review Rating']

df.info()

df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

df.columns

# Create a colum age_group
labels=['Young Adult','Adult','Middle-aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

df.info()

df[['age','age_group']].head(10)

#create columns purchase_frequency_days
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90

}

df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

df[['purchase_frequency_days','frequency_of_purchases']].head(10)

df.isnull().sum()

df[['discount_applied','promo_code_used']].head(10)

(df['discount_applied']==df['promo_code_used']).all()

df=df.drop('promo_code_used',axis=1)

df.columns

df.to_csv('clean data Customer_Shooping.csv',index=False)

