create database CustomerShopping
select * from DataFile

--what is the total revenue generated by Male Vs Female customers.
select 
	gender,
	sum(purchase_amount) as TotalRevenue
from DataFile
group by gender

--which customer used a discount but still spend more than the average purchase amount.

select 
customer_id,
purchase_amount
from DataFile 
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from DataFile)

--which are the top 5 products with the highest ave review rating
select 
item_purchased,
round(avg(review_rating),2) as avgrating
from DataFile
group by item_purchased


--compare the avg puchase amount b/w standard and express shipping
select 
shipping_type,
avg(purchase_amount) as avgamount
from DataFile
where shipping_type in ('Standard','Express')
group by shipping_type 

--do subscriber customer spend more? compare average spend and 
--total revenue b/w subscriber and non subscriber 
select 
customer_id,
subscription_status,
avg(purchase_amount) over(partition by subscription_status)as AvgAmount,
sum(purchase_amount) over(partition by subscription_status) as TotalAmount
from DataFile

--which 5 product have the the highest percentage of purchase with discount applied
select top 5
item_purchased,
round(100*sum(case when discount_applied ='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from DataFile
group by item_purchased
order by discount_rate desc

--segment customers into new, returning,and loyal based on their total
--num of previous purchase, and show the count of each segment.

select * from DataFile

with customer_type as (
select customer_id,
     previous_purchases,
case 
     when previous_purchases=1 then 'New'
	 when previous_purchases between 2 and 10 then 'Returning'
	 else 'loyal'
end as Customer_Segments
from DataFile
)

select Customer_Segments, count(*) as "NumberOFCustomers"
from customer_type 
group by Customer_Segments

--what are the top 3 most purchased products within each category..

with item_counts as 
(
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from DataFile
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3

--are customers who are repeat buyers (more than 5 previous pruchases ) also likely to subscribe?
select 
	count(customer_id),	
	subscription_status
from DataFile
where previous_purchases >5 
group by subscription_status

select * from DataFile 

--what is the revenue contrubutio of each age group
Select
age_group,
sum(purchase_amount) as Total_Sum
from 
DataFile
group by age_group